language: node_js
node_js:
  - "10.15.3"
  - "13.2.0"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b98f41fd6ac7d5740632
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false